### ISSUE TITLE
0.8.1 is not published

### ISSUE THREAD

**Issue by granthenke** [ngbinh/gradle-scalastyle-plugin#16]
https://jcenter.bintray.com/org/github/ngbinh/scalastyle/gradle-scalastyle-plugin_2.11/

**Comment by ngbinh** [comment]
fixed. Thanks for reporting https://dl.bintray.com/ngbinh/maven/org/github/ngbinh/scalastyle/gradle-scalastyle-plugin_2.11/0.8.1/
