### ISSUE TITLE
0.8.1 does not generate violations

### ISSUE THREAD

**Issue by granthenke** [ngbinh/gradle-scalastyle-plugin#18]
I upgraded from 0.7.2 to 0.8.1 and can't make a violation error occur. 

I simplified my project down to a configuration with only 1 check, and a file that should fail, and still no failure.

**Comment by tzachz** [comment]
Same here... downgraded back to 0.7.2... 
BTW, I'm using Scala 2.10 version: `org.github.ngbinh.scalastyle:gradle-scalastyle-plugin_2.10:0.8.1`

**Comment by hntd187** [comment]
I also can't produce any violations, but I'm using the 2.11 version.

**Comment by ngbinh** [comment]
Sorry guys! Will look into it this week.
