### ISSUE TITLE
Support scala 2.12

### ISSUE THREAD

**Issue by otrosien** [ngbinh/gradle-scalastyle-plugin#31]
Please add scala 2.12 support with the next release.

**Comment by jcranky** [comment]
Any plans for this to actually happen?

**Comment by srmds** [comment]
Any plans for the above plans to make add support for Scala 2.12 actually happen?

**Comment by tomnis** [comment]
we'd really like 2.12 support also :)

**Comment by ngbinh** [comment]
ok, will try to get this done soon.

**Comment by ngbinh** [comment]
https://github.com/ngbinh/gradle-scalastyle-plugin/commit/94d5ecc655555efb8705f4f6f2344a897afd7d68

**Comment by jcranky** [comment]
Thanks :)

**Comment by jcranky** [comment]
@ngbinh Is this published yet or when would it be published? :)

**Comment by ngbinh** [comment]
Let me check when I get home

**Comment by jcranky** [comment]
Thanks again :)

**Comment by ngbinh** [comment]
should be available here https://bintray.com/ngbinh/maven/gradle-scalastyle-plugin_2.12/1.0.0 . I forgot to push the button, sorry for that!

**Comment by tomnis** [comment]
cool, thanks a lot :)

**Comment by tomnis** [comment]
hi @ngbinh sorry, but it looks like this new published artifact is not resolvable from jcenter.

```
 > Could not find org.github.ngbinh.scalastyle:gradle-scalastyle-plugin_2.12:1.0.0.
     Searched in the following locations:
         https://jcenter.bintray.com/org/github/ngbinh/scalastyle/gradle-scalastyle-plugin_2.12/1.0.0/gradle-scalastyle-plugin_2.12-1.0.0.pom
         https://jcenter.bintray.com/org/github/ngbinh/scalastyle/gradle-scalastyle-plugin_2.12/1.0.0/gradle-scalastyle-plugin_2.12-1.0.0.jar
```

I have a small example buildscript here: https://github.com/tomnis/scalastyle-gradle-not-resolved

Looking at the 2.12 artifact in bintray, I don't think its linked to the jcenter repository:
![screenshot 2017-10-05 13 03 39](https://user-images.githubusercontent.com/1219411/31249865-d226add0-a9cd-11e7-8bfe-01f5cfb1c9fa.png)

The older 2.11 artifacts are linked to jcenter:
![screenshot 2017-10-05 13 06 47](https://user-images.githubusercontent.com/1219411/31249950-21773e5e-a9ce-11e7-84fe-6cb0a23aebcf.png)


Could you link the new 2.12 artifact to jcenter please?

**Comment by jcranky** [comment]
Linking to jcenter would be useful indeed. In the mean while, I managed to use it by adding this to my `build.gradle` file, in the `buildscript.repositories` section:

```groovy
maven {
    name = "ngbinh"
    url = "https://dl.bintray.com/ngbinh/maven"
}
```

**Comment by ngbinh** [comment]
I already made the request for the `2.12` artifact to be linked. Hopefully it will appear there soon. In the mean time, please use @jcranky workaround.

**Comment by gregschibsted** [comment]
Any chance of publishing for 2.11 too, with the latest fix?

**Comment by howyp** [comment]
Hey @ngbinh, I still can't see the 2.12 artifact in JCenter :-( Would you be able to check what's up, please?

**Comment by ngbinh** [comment]
@howyp I already see this
![screen shot 2017-11-17 at 6 13 56 pm](https://user-images.githubusercontent.com/211327/32944757-2f0557e2-cbc3-11e7-9e6a-e17e6542a3cd.png)

Not sure what else I have to do?

**Comment by ngbinh** [comment]
@gregschibsted will do this week.

**Comment by howyp** [comment]
Hmmm that's odd. I see this in JCenter:

<img width="478" alt="screen shot 2017-11-17 at 11 23 19" src="https://user-images.githubusercontent.com/4593903/32945139-305098e8-cb8a-11e7-9a2b-603ac1f61ff2.png">
