### ISSUE TITLE
ScalaStyle Now 1.0

### ISSUE THREAD

**Issue by neilchaudhuri** [ngbinh/gradle-scalastyle-plugin#32]
Is there a plan to upgrade the plugin to use the latest Scalastyle? Or better yet, is there a way to configure the version the plugin will use?

Thanks.

**Comment by ngbinh** [comment]
fixed in https://github.com/ngbinh/gradle-scalastyle-plugin/commit/94d5ecc655555efb8705f4f6f2344a897afd7d68
