### ISSUE TITLE
cannot find the plugin version 1.0.0 in jcenter

### ISSUE THREAD

**Issue by ChinLong** [ngbinh/gradle-scalastyle-plugin#37]
forget to publish?:sweat_smile:

**Comment by jcranky** [comment]
It is not there indeed: http://jcenter.bintray.com/org/github/ngbinh/scalastyle/gradle-scalastyle-plugin_2.11/

**Comment by jcranky** [comment]
It is there for 2.12 apparently: https://bintray.com/bintray/jcenter?filterByPkgName=gradle-scalastyle-plugin_2.12 :)

**Comment by jcranky** [comment]
I mean, it is there for 2.12, but not for 2.11. Or did something change?

**Comment by ChinLong** [comment]
oh...  sorry....   I use the 2.12. neglected the 2.11...
how to reopen the issue?
