### ISSUE TITLE
Gradle pre-defaulting 2.8 library when running scalastyle-plugin

### ISSUE THREAD

**Issue by scubapup** [ngbinh/gradle-scalastyle-plugin#6]
Given the sample build.gradle buildscript entries, the script is failing when running scalaStyle because it is at some point unable to load Scala.predef..colon less colon..

Classloader logs show that gradle is loading scala library 2.8 which is in the gradle init.d directory

Have you seen this issue before and do you have suggestions on how to make this work for the 2.11 build of this plugin?

**Comment by ngbinh** [comment]
It looks to me like your `build.grade` tried to load Scala 2.8. It is super old and isn't supported by this plugin. My only suggestion is to upgrade the build Scala version to at least `2.10`

**Comment by scubapup** [comment]
Thanks for responding. We dug a bit and looks like a custom initializer in our gradle install is adding the bad dependency.
